project_id = "tzxvlfemmamhrxtcqfhz"

[functions.generate-blog-content]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.razorpay-create-order]
verify_jwt = true

[functions.razorpay-verify-payment]
verify_jwt = true
