// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzxvlfemmamhrxtcqfhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6eHZsZmVtbWFtaHJ4dGNxZmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzEwODUsImV4cCI6MjA2NTcwNzA4NX0.wHrtKZiGgo90Ffle_AgeJtJLzqJYv3wEje3QU0epPOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);